package Principal.Menu;

/**
 *
 * @author CJ
 */
public class Work extends javax.swing.JPanel {

    /**
     * Creates new form Simple
     */
    public Work() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new Principal.Menu.Elements.MenuBar();
        titleBar1 = new Principal.Menu.Elements.TitleBar();
        statusBar1 = new Principal.Menu.Elements.StatusBar();
        toolBar1 = new Principal.Menu.Elements.ToolBar();
        navigationPanel1 = new Principal.Menu.Elements.NavigationPanel();
        tabList1 = new Principal.Menu.Elements.TabList();
        filterBar1 = new Principal.Menu.Elements.FilterBar();
        tabBar1 = new Principal.Menu.Elements.TabBar();
        deskPanel1 = new Principal.Menu.Elements.DeskPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBar1.setBackground(new java.awt.Color(153, 0, 0));
        menuBar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBar1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout titleBar1Layout = new javax.swing.GroupLayout(titleBar1);
        titleBar1.setLayout(titleBar1Layout);
        titleBar1Layout.setHorizontalGroup(
            titleBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        titleBar1Layout.setVerticalGroup(
            titleBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        menuBar1.add(titleBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 440, 30));

        add(menuBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));

        statusBar1.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout statusBar1Layout = new javax.swing.GroupLayout(statusBar1);
        statusBar1.setLayout(statusBar1Layout);
        statusBar1Layout.setHorizontalGroup(
            statusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        statusBar1Layout.setVerticalGroup(
            statusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        add(statusBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 396, 679, -1));

        toolBar1.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout toolBar1Layout = new javax.swing.GroupLayout(toolBar1);
        toolBar1.setLayout(toolBar1Layout);
        toolBar1Layout.setHorizontalGroup(
            toolBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        toolBar1Layout.setVerticalGroup(
            toolBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(toolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 679, -1));

        navigationPanel1.setBackground(new java.awt.Color(51, 255, 51));
        navigationPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabList1.setBackground(new java.awt.Color(255, 0, 255));

        javax.swing.GroupLayout tabList1Layout = new javax.swing.GroupLayout(tabList1);
        tabList1.setLayout(tabList1Layout);
        tabList1Layout.setHorizontalGroup(
            tabList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        tabList1Layout.setVerticalGroup(
            tabList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );

        navigationPanel1.add(tabList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, -1, -1));

        filterBar1.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout filterBar1Layout = new javax.swing.GroupLayout(filterBar1);
        filterBar1.setLayout(filterBar1Layout);
        filterBar1Layout.setHorizontalGroup(
            filterBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        filterBar1Layout.setVerticalGroup(
            filterBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        navigationPanel1.add(filterBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 138, -1));

        add(navigationPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 320));

        tabBar1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout tabBar1Layout = new javax.swing.GroupLayout(tabBar1);
        tabBar1.setLayout(tabBar1Layout);
        tabBar1Layout.setHorizontalGroup(
            tabBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        tabBar1Layout.setVerticalGroup(
            tabBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(tabBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 530, 30));

        deskPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout deskPanel1Layout = new javax.swing.GroupLayout(deskPanel1);
        deskPanel1.setLayout(deskPanel1Layout);
        deskPanel1Layout.setHorizontalGroup(
            deskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        deskPanel1Layout.setVerticalGroup(
            deskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        add(deskPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 530, 290));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Principal.Menu.Elements.DeskPanel deskPanel1;
    private Principal.Menu.Elements.FilterBar filterBar1;
    private Principal.Menu.Elements.MenuBar menuBar1;
    private Principal.Menu.Elements.NavigationPanel navigationPanel1;
    private Principal.Menu.Elements.StatusBar statusBar1;
    private Principal.Menu.Elements.TabBar tabBar1;
    private Principal.Menu.Elements.TabList tabList1;
    private Principal.Menu.Elements.TitleBar titleBar1;
    private Principal.Menu.Elements.ToolBar toolBar1;
    // End of variables declaration//GEN-END:variables
}
